<?php

require_once dirname(__FILE__) . '/../../../../../../../subtabs/Classes/User/Func.php';

/**
 * Test class for Tx_Subtabs_User_Func.
 * Generated by PHPUnit on 2011-06-14 at 14:05:59.
 */
class Tx_Subtabs_User_FuncTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Tx_Subtabs_User_Func
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Tx_Subtabs_User_Func;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testUser_getNelConfig().
	 */
	public function testUser_getNelConfig() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
